Name: Soji Ademiluyi  
Email: aademilu@uncc.edu

Subtract the 1D Array *arr2* from the 2D array *arr1*, such that each item of *arr2* subtracts from respective row of *arr1*

Ex

arr1 = `[[x1, x2 , x3], [y1, y2, y3], [z1,z2,z3]]`

arr2 = `[x,y,z]`

Result `[ [ x1-x, x2-x, x3-x],` etc

In [2]:
import numpy as np

In [6]:
arr1 = np.array(range(1,10))
arr1 = arr1.reshape(3,3)
arr2 = np.array(range(1,4))
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
arrx = arr1.T - arr2
arrx = arrx.T
arrx

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

Given a 1D Array, find the local maxima (numbers surrounded by 2 smaller numbers)

In [13]:
arr3 = np.arange(20)
arr3[6], arr3[14], arr3[17] = 10, 20, 50
arr3

array([ 0,  1,  2,  3,  4,  5, 10,  7,  8,  9, 10, 11, 12, 13, 20, 15, 16,
       50, 18, 19])

In [9]:
for i in range(len(arr3)-1):
    if arr3[i] > arr3[i-1] and arr3[i] > arr3[i+1]:
        print(arr3[i])
        continue

10
20
50


Given two n x m Arrays, compute the average of elements in matching subarrays

Ex

arr1      
`[[1,1],[2,2],[3,3]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[1,2,3]`



In [89]:
arr4 = np.arange(6).reshape(3,2)
arr5 = np.arange(6).reshape(3,2)
print(arr5, arr4)

[[0 1]
 [2 3]
 [4 5]] [[0 1]
 [2 3]
 [4 5]]


In [88]:
arr6 = arr5 + arr4
arrAvg = []
for i in arr6:
    arrAvg.append(i.sum()/2)
arrAvg
    

[1.0, 5.0, 9.0]