Name: Adesoji Ademiluyi  
Email: aademilu@uncc.edu

Notes on Numpy usage and purposing.

Numpy is a package for scientific computing and data manipulation. It contains many functions for sorting, selecting within and array, linear algebra, statistic and more. It revolves around the ndarray object which is an array of n-dimensions that is homogeneous across data type and intialized with a fixed size. 

As general practice we can 
 `import numpy as np` for quick calling of numpy.

In [3]:
import numpy as np

There are various ways you can create a numpy array. When we create an array the data type is inferred.

In [15]:
n = np.array([2, 3, 4])
r = np.array([2.2, 3.3, 4.4])
m = np.array([2,3,4.4])
n.dtype

dtype('int32')

In [16]:
m.dtype

dtype('float64')

Notice when we check the data type for m the integers are automatically converted to floats.

In [20]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
x = np.arange(1,100,2)
x.size

50

`np.zeroes` and similar numbered functions create an array of those specific values.  
`np.arange` can create an array with specific steps through a range of values.  
`np.reshape` creates an array of the given size given the target array has contents of compatible dimensions.

In [21]:
x.shape

(50,)

In [5]:
y = x.reshape(5,10)

In [27]:
y.shape

(5, 10)

In [29]:
y

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

We can also transpose an array by using the `T` method.  
The result is 10 rows and 5 columns. 10 along axis 0 and 5 along axis 1.

In [16]:
y = y.T

In [17]:
y.shape

(10, 5)

In [18]:
y

array([[ 1, 21, 41, 61, 81],
       [ 3, 23, 43, 63, 83],
       [ 5, 25, 45, 65, 85],
       [ 7, 27, 47, 67, 87],
       [ 9, 29, 49, 69, 89],
       [11, 31, 51, 71, 91],
       [13, 33, 53, 73, 93],
       [15, 35, 55, 75, 95],
       [17, 37, 57, 77, 97],
       [19, 39, 59, 79, 99]])

# Axis
Axis is a importnat way of describing arrays in the numpy system.

`axis=None` describes operations done on an array that moves through every value of every row and column. This means that we ignore the concept of an axis and apply an operation array-wise.  
`axis=0` describes operations done on an array row wise. We apply operations for every row in the array, per column in the array. This produces a value for each column we have.  
`axis=1` describes operations done on an array column wise. We apply operations for every column in the array, per row in the array. This produces a value for each row we have.  
`axis=n` as we decrease the dimensionality of our array, we can continue to perform further operations across the new dimensions.  
**In the way axes are presented to us in numpy, we can see them as dimensions nested within one another in structure.**

### Linear Algebra Operations

Two arrays can be multiplied with the `*` operator. this functions element wise.
`@` and `x.dot(y)` can be used for general matrix multiplication with implicit transposition.  
  
Additionally, a large amount of functions can be performed element wise:   
`+=`, `-=` and `*=`, `/=` can be used to modify existing arrays from arrays of equal dimensions.  


In [6]:
x.max()

99

In [7]:
x.min()

1

Here we perform a sum that returns a single numerical value.

In [8]:
x.sum()

2500

We can perform this same functions along axis 1, which returns the maximum of all the column entries for each row of the 5 x 10 matrix.

In [10]:
y.max(axis=1)

array([19, 39, 59, 79, 99])

### Indexing

We can find specific values in an array by accessing their index.

`y[5]` by default gives us the 6th value (indexes start with 0) of the 0th axis.

In [23]:
y[5]

array([11, 31, 51, 71, 91])

Additional axes are separated by commas, here we retrieve the 3rd value in the previously selected axis=0 entry.

In [24]:
y[5,2]

51

A `:` includes everything in the range before or after a specific index. The ending point in this range (called a slice) is not inclusive.

In [21]:
y[5,:2]

array([11, 31])

To get up to the value we found before, we must include the index after our desired stop point.

In [25]:
y[5,:3]

array([11, 31, 51])